### ISSUE TITLE
Issue with NameID generation in 4.2.1 / multiple source attribute of nameID

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxShibboleth#75] opened 2020-08-28 21:05 UTC
**Target**

This test sp require `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` format nameID to be generated and sent back to SP from Gluu Server. 

**Situation in 4.2.1**

I am trying to configure nameID with [oxTrust](https://www.gluu.org/docs/gluu-server/4.2/admin-guide/saml/#configure-nameid-in-oxtrust), setup looks like below: 
![nameID](https://user-images.githubusercontent.com/7156097/91614679-99c51000-e947-11ea-8e91-17b6dcf7768b.PNG)

In Trust Relationship, I used 'SAML2SSO' profile's new feature "SAML NameID permission" as well. 

![Capture](https://user-images.githubusercontent.com/7156097/91614691-a0538780-e947-11ea-9cf4-7c7b28e8b701.PNG)

But after doing that, my SP is getting 'multiple' emailAddress . Here is what "idp-process.log" looks like:

```
2020-08-28 20:53:52,197 - 103.19.130.250 - DEBUG [org.opensaml.saml.saml2.profile.impl.AddNameIDToSubjects:284] - Profile Action AddNameIDToSubjects: Attempting to add NameID to outgoing Assertion Subjects
2020-08-28 20:53:52,198 - 103.19.130.250 - DEBUG [org.opensaml.saml.saml2.profile.impl.AddNameIDToSubjects:314] - Profile Action AddNameIDToSubjects: Request specified NameID format: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
2020-08-28 20:53:52,198 - 103.19.130.250 - DEBUG [org.opensaml.saml.saml2.profile.impl.AddNameIDToSubjects:393] - Profile Action AddNameIDToSubjects: Trying to generate NameID with Format urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
2020-08-28 20:53:52,198 - 103.19.130.250 - DEBUG [org.opensaml.saml.common.profile.impl.ChainingNameIdentifierGenerator:103] - Trying to generate identifier with Format urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
2020-08-28 20:53:52,198 - 103.19.130.250 - DEBUG [net.shibboleth.idp.saml.nameid.impl.AttributeSourcedSAML2NameIDGenerator:191] - Checking for source attribute mail
2020-08-28 20:53:52,198 - 103.19.130.250 - DEBUG [net.shibboleth.idp.saml.nameid.impl.AttributeSourcedSAML2NameIDGenerator:210] - Generating NameID from String-valued attribute mail
2020-08-28 20:53:52,199 - 103.19.130.250 - DEBUG [org.opensaml.saml.saml2.profile.AbstractSAML2NameIDGenerator:95] - Generating NameID mohib@gluu.org with Format urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
2020-08-28 20:53:52,199 - 103.19.130.250 - DEBUG [org.opensaml.saml.common.profile.impl.ChainingNameIdentifierGenerator:115] - Successfully generated identifier with Format urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
2020-08-28 20:53:52,199 - 103.19.130.250 - DEBUG [org.opensaml.saml.saml2.profile.impl.AddNameIDToSubjects:397] - Profile Action AddNameIDToSubjects: Successfully generated NameID with Format urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
2020-08-28 20:53:52,199 - 103.19.130.250 - DEBUG [org.opensaml.saml.saml2.profile.impl.AddNameIDToSubjects:355] - Profile Action AddNameIDToSubjects: Added NameID to 1 assertion subject(s)
.....
.....
......
        <saml2:Subject>
            <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">mohib@gluu.org</saml2:NameID>
            <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml2:SubjectConfirmationData Address="103.19.130.250" InResponseT......
.....
......
        <saml2:AuthnStatement AuthnInstant="2020-08-28T20:53:52.108Z" SessionIndex="_d2e0c209b665cb2962822dc51e790c9c">
            <saml2:SubjectLocality Address="103.19.130.250"/>
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
        <saml2:AttributeStatement>
            <saml2:Attribute FriendlyName="uid" Name="urn:oid:0.9.2342.19200300.100.1.1" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xsd:string">zico</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="mail" Name="$attrParams.attributeSAML2Strings.get($attribute.name)" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue>mohib@gluu.org</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute FriendlyName="mail" Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xsd:string">mohib@gluu.org</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
    </saml2:Assertion>
</saml2p:Response>

2020-08-28 20:53:52,259 - 103.19.130.250 - DEBUG [net.shibboleth.idp.profile.impl.RecordResponseComplete:89] - Profile Action RecordResp....
.....
.....
```

**Comment by malotian** [comment] 2020-08-31 03:11
duplicate of https://github.com/GluuFederation/oxAuth/issues/1411

**Closed** 2020-09-23 13:26 UTC
Labels: High Priority, bug
